//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFSuperMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public string BarCode { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public long UnitPrice { get; set; }
        public long TotalPrice { get; set; }
        public long DiscountPrice { get; set; }
        public long VATPrice { get; set; }
        public long PaidPrice { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Order Order { get; set; }
    }
}
