//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFSuperMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int Id { get; set; }
        public string BarCode { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int AccountId { get; set; }
        public int Status { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeId { get; set; }
        public long Price { get; set; }
        public string Picture { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> ExpiredTime { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
